### ISSUE TITLE
not sure how to use it

### ISSUE THREAD

**Issue by ctf0** [rubikonx9/SublimeRegexExplainTip#1]
lets say i have something like

```
[\\w\\-:]+(?:\\s*=\\s*(?:\"[^\"]*\"|'[^']*'))?
```

how to use the package with something like this ?

**Comment by rubikonx9** [comment]
Are you on Linux or Windows? Have you installed the prerequisites (Perl with `YAPE::Regex::Explain` module)?

In general, select the text (entire regex), then press `alt+r`, and you should see the explanation.
If it doesn't work this way, could you check the console output (open it with `ctrl+backtick`) for errors?

**Comment by ctf0** [comment]
am on mac , and dont know how to install the `YAPE::Regex::Explain` module, having this part in the readme would be a great help for anyone noobie like myself.

**Comment by rubikonx9** [comment]
Please start here: http://www.cpan.org/modules/INSTALL.html
Unfortunately I don't have a Mac machine available to me, so this is generally untested... Please let me know if you manage to make it work.

**Comment by ctf0** [comment]
honestly this is too much work to get something so simple like this to work, thanx still.
