### ISSUE TITLE
Windows Use

### ISSUE THREAD

**Issue by caleywoods** [rubikonx9/SublimeRegexExplainTip#6]
Ran into the `no YAPE::Regex::Explain` issue on windows after installing Strawberry PERL and using its built in CPAN client to install both YAPE::Regex and YAPE::Regex::Explain. 

Had to end up adding 
`use lib 'c:/StrawberryPERL/perl/site/lib';`

To RegexExplainTip.py which allows `@INC` to include that path when the command is executed as part of the `get_explanation()` method. Thought this might be something useful to include in the wiki, the user just needs to find out where ActiveState PERL or Strawberry PERL installs CPAN modules to and then point to that path in the command.

**Comment by rubikonx9** [comment]
Hello.
This seems to be a Perl installation issue, not directly related to the plugin itself.
I think it'd be enough if I add appropriate info about the potential problem in the README.
Agreed?

**Comment by caleywoods** [comment]
Sure that would be fine, if you just want to reference this issue that would work as well. Have a great week.
