### ISSUE TITLE
in my win10 system it's not work

### ISSUE THREAD

**Issue by Barton0403** [rubikonx9/SublimeRegexExplainTip#7]
I have install `YAPE-Regex-Explain-4.01`, but when I press <kbd>shift</kbd>+<kbd>win</kbd>+<kbd>alt</kbd>+<kbd>R</kbd>, it still didn't work. No any tip.

system: win10
version: sublime text 3 build 3143

**Comment by rubikonx9** [comment]
Hello.
It seems that the key configuration is invalid.
Could you please try pressing <kbd>Alt</kbd>+<kbd>r</kbd> and see if anything happens?

**Comment by rubikonx9** [comment]
Turns out the keymap change hasn't been released.
I've made a release of a new version, please verify after you get an update from Package Control.

**Comment by rubikonx9** [comment]
I'm closing the issue as I got no answer.
